server:
  servlet:
    #contextPath: /auth-service
    contextPath: /
  port: 8089

#DB Config
spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

springdoc:
  packagesToScan: com.mdtlabs.coreplatform.authserver

eureka:
  client:
    serviceUrl:
      defaultZone: http://servicediscovery:8761/eureka/

app:
  swagger-server-url: http://localhost:8089/
  public-key: public_key.der
  private-key: private_key.der
  login-time-limit-in-hour: ${LOGIN_TIME_LIMIT_IN_HOUR:1}
  login-count-limit: ${LOGIN_COUNT_LIMIT:5}
  password: ${PASSWORD}
spicelog:
  fileName: './log/SpiceApplicationLog.log'
  fileNamePattern: './log/SpiceApplicationLog.%d{yyyy-MM-dd}.log.gz'
  consolePattern: '%white(%d{ISO8601}) %highlight(%-5level) [%yellow(%t)] :  %msg%n%throwable'
  filePattern: ' %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  maxHistory: 30
  totalSizeCap: 3GB
